name: Cut a new release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Please input any text for confirmation'
        required: true

jobs:
  release:
    needs: [clj_style, clj_kondo]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk
          architecture: x64

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.1040'

      - name: Show versions
        run: |
          java -version
          clojure --version

      - name: Cache dependencies
        uses: toyokumo/cache@main
        with:
          path: |
            ~/.m2
          key: clj-cache-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            clj-cache-

      - name: Run tests
        run: make release
